/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as MarketUpdateRouteImport } from './routes/market-update'
import { Route as PhysicalSilverRouteImport } from './routes/physical-silver'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SilverIraRouteImport } from './routes/silver-ira'
import { Route as SilverSupplyRouteImport } from './routes/silver-supply'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhySilverRouteImport } from './routes/why-silver'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketUpdateRoute = MarketUpdateRouteImport.update({
  id: '/market-update',
  path: '/market-update',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalSilverRoute = PhysicalSilverRouteImport.update({
  id: '/physical-silver',
  path: '/physical-silver',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverIraRoute = SilverIraRouteImport.update({
  id: '/silver-ira',
  path: '/silver-ira',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverSupplyRoute = SilverSupplyRouteImport.update({
  id: '/silver-supply',
  path: '/silver-supply',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhySilverRoute = WhySilverRouteImport.update({
  id: '/why-silver',
  path: '/why-silver',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/market-update': typeof MarketUpdateRoute
  '/physical-silver': typeof PhysicalSilverRoute
  '/privacy': typeof PrivacyRoute
  '/silver-ira': typeof SilverIraRoute
  '/silver-supply': typeof SilverSupplyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/why-silver': typeof WhySilverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/market-update': typeof MarketUpdateRoute
  '/physical-silver': typeof PhysicalSilverRoute
  '/privacy': typeof PrivacyRoute
  '/silver-ira': typeof SilverIraRoute
  '/silver-supply': typeof SilverSupplyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/why-silver': typeof WhySilverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/market-update': typeof MarketUpdateRoute
  '/physical-silver': typeof PhysicalSilverRoute
  '/privacy': typeof PrivacyRoute
  '/silver-ira': typeof SilverIraRoute
  '/silver-supply': typeof SilverSupplyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/why-silver': typeof WhySilverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/get-started'
    | '/market-update'
    | '/physical-silver'
    | '/privacy'
    | '/silver-ira'
    | '/silver-supply'
    | '/sitemap.xml'
    | '/terms'
    | '/why-silver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/get-started'
    | '/market-update'
    | '/physical-silver'
    | '/privacy'
    | '/silver-ira'
    | '/silver-supply'
    | '/sitemap.xml'
    | '/terms'
    | '/why-silver'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/get-started'
    | '/market-update'
    | '/physical-silver'
    | '/privacy'
    | '/silver-ira'
    | '/silver-supply'
    | '/sitemap.xml'
    | '/terms'
    | '/why-silver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  GetStartedRoute: typeof GetStartedRoute
  MarketUpdateRoute: typeof MarketUpdateRoute
  PhysicalSilverRoute: typeof PhysicalSilverRoute
  PrivacyRoute: typeof PrivacyRoute
  SilverIraRoute: typeof SilverIraRoute
  SilverSupplyRoute: typeof SilverSupplyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WhySilverRoute: typeof WhySilverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-update': {
      id: '/market-update'
      path: '/market-update'
      fullPath: '/market-update'
      preLoaderRoute: typeof MarketUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-silver': {
      id: '/physical-silver'
      path: '/physical-silver'
      fullPath: '/physical-silver'
      preLoaderRoute: typeof PhysicalSilverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver-ira': {
      id: '/silver-ira'
      path: '/silver-ira'
      fullPath: '/silver-ira'
      preLoaderRoute: typeof SilverIraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver-supply': {
      id: '/silver-supply'
      path: '/silver-supply'
      fullPath: '/silver-supply'
      preLoaderRoute: typeof SilverSupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-silver': {
      id: '/why-silver'
      path: '/why-silver'
      fullPath: '/why-silver'
      preLoaderRoute: typeof WhySilverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  GetStartedRoute: GetStartedRoute,
  MarketUpdateRoute: MarketUpdateRoute,
  PhysicalSilverRoute: PhysicalSilverRoute,
  PrivacyRoute: PrivacyRoute,
  SilverIraRoute: SilverIraRoute,
  SilverSupplyRoute: SilverSupplyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WhySilverRoute: WhySilverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
