onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - unrs-resolver
  - sharp
  - esbuild
  - "@parcel/watcher"
  - workerd
allowBuilds:
  unrs-resolver: true
  "@tailwindcss/oxide": true
  sharp: true
  esbuild: true
  "@parcel/watcher": true
  workerd: true
